/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_getpic_GetPicUsingJni */

#ifndef _Included_com_getpic_GetPicUsingJni
#define _Included_com_getpic_GetPicUsingJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_getpic_GetPicUsingJni
 * Method:    getPicFromFrameBuffer
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_syouquan_script_ColorEngine_nativeScreenShot
  (JNIEnv *, jobject, jstring path);

JNIEXPORT jint JNICALL Java_com_syouquan_script_ColorEngine_nativeGetColor
  (JNIEnv *, jobject, jint x, jint y);

#ifdef __cplusplus
}
#endif
#endif
